-- Add migration script here
CREATE TABLE IF NOT EXISTS channels
(
    name VARCHAR PRIMARY KEY NOT NULL,
    id BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages
(
	name VARCHAR PRIMARY KEY NOT NULL,
	id BIGINT NOT NULL,
	channel_id BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS help_categories
(
    id BIGINT PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS help_channels
(
    id BIGINT PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL
);